### ISSUE TITLE
Getting error on cart.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [wpswings/subscriptions-for-woocommerce#126]
WordPress version: 5.8
WooCommerce version: 5.6
Plugin Compatibility: MWB Multi Currency Switcher For WooCommerce <-> MWB Role Based Pricing For WooCommerce
Area Path: Store-end-> Cart
Version: 1.1.0
Description: Getting error on shop & cart having Subscription product with MWB Multi Currency Switcher For WooCommerce plugin.
![Screenshot (78)](https://user-images.githubusercontent.com/76723329/131111049-ba91d1f3-b45c-4ef8-b369-699a2c97b0ca.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
