### ISSUE TITLE
Remove Filter

### ISSUE THREAD

**Issue by igoragatti** [wpswings/subscriptions-for-woocommerce#147]
Hi there! First of all thank you for developing this wonderful plugin.

I've been having trouble removing a filter, and was wondering:

Do I have to add `global $sfw_plugin_public;` to the top of the following function to be able to call the filter `private function subscriptions_for_woocommerce_public_hooks()`? Should I try to remove the filter some other way?

If I don't leave in the `global` declaration at the top of the function, when I try to call the variable in the functions.php file in my theme, the variable comes empty.

**Comment by indresh-cedcoss** [comment]
Hi @igoragatti 
you can use the following code in your theme's functions.php to remove the filter.

add_action('wp_head','mwb_remove_hook_filter');
 function mwb_remove_hook_filter() {
 	
 	mwb_remove_filters('hook_name','method_name', 'priority');
 	
 }

function mwb_remove_filters( $hook_name = '', $method_name = '', $priority = 0 ) {
	global $wp_filter;

	// Take only filters on right hook name and priority
	if ( ! isset( $wp_filter[ $hook_name ][ $priority ] ) || ! is_array( $wp_filter[ $hook_name ][ $priority ] ) ) {
		return false;
	}

	foreach ( (array) $wp_filter[ $hook_name ][ $priority ] as $unique_id => $filter_array ) {
		
		if ( isset( $filter_array['function'] ) && is_array( $filter_array['function'] ) ) {
			
			if ( is_object( $filter_array['function'][0] ) && get_class( $filter_array['function'][0] ) && $filter_array['function'][1] == $method_name ) {
				if ( is_a( $wp_filter[ $hook_name ], 'WP_Hook' ) ) {
					unset( $wp_filter[ $hook_name ]->callbacks[ $priority ][ $unique_id ] );
				} else {
					unset( $wp_filter[ $hook_name ][ $priority ][ $unique_id ] );
				}
			}
		}

	}
	return false;
}

**Comment by igoragatti** [comment]
> Hi @igoragatti you can use the following code in your theme's functions.php to remove the filter.
> 
> add_action('wp_head','mwb_remove_hook_filter'); function mwb_remove_hook_filter() {
> 
> ```
> mwb_remove_filters('hook_name','method_name', 'priority');
> ```
> 
> }
> 
> function mwb_remove_filters( $hook_name = '', $method_name = '', $priority = 0 ) { global $wp_filter;
> 
> ```
> // Take only filters on right hook name and priority
> if ( ! isset( $wp_filter[ $hook_name ][ $priority ] ) || ! is_array( $wp_filter[ $hook_name ][ $priority ] ) ) {
> 	return false;
> }
> 
> foreach ( (array) $wp_filter[ $hook_name ][ $priority ] as $unique_id => $filter_array ) {
> 	
> 	if ( isset( $filter_array['function'] ) && is_array( $filter_array['function'] ) ) {
> 		
> 		if ( is_object( $filter_array['function'][0] ) && get_class( $filter_array['function'][0] ) && $filter_array['function'][1] == $method_name ) {
> 			if ( is_a( $wp_filter[ $hook_name ], 'WP_Hook' ) ) {
> 				unset( $wp_filter[ $hook_name ]->callbacks[ $priority ][ $unique_id ] );
> 			} else {
> 				unset( $wp_filter[ $hook_name ][ $priority ][ $unique_id ] );
> 			}
> 		}
> 	}
> 
> }
> return false;
> ```
> 
> }

Hi @indresh-cedcoss,

Thank you for your reply, the proposed solution didn't solve the issue for me, it seems like the filter is still activated.
