### ISSUE TITLE
Renewal payment are not completed via stripe 

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#167]
**Bug Name -**Renewal payment are not completed via stripe 
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 1.3.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/155830660-5201a17b-8b23-49f8-92a0-d5f403818b2d.png)

![image](https://user-images.githubusercontent.com/76723393/155830683-f781fa6d-a0d6-4ddf-9e53-28a925de4496.png)

**Comment by Shivamddeveloper** [comment]
sir,please watch attached screen recording video beacuse that problem is occuring in mysetup

[https://www.awesomescreenshot.com/video/7632777?key=a84dc47e20f5bfe18dc6c634ff9f8a21](url)

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
