### ISSUE TITLE
Migration Issue 

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#168]
**Bug Name -** Migration Issue 
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 1.3.2
**Description -**

If anyone is using the previous version of the plugin and then updating the plugin, all running subscriptions are missed.
and then 
If you buying the subscription then in my account subscription tab are not opening.

![image](https://user-images.githubusercontent.com/76723393/156124783-fe4b8bcf-240f-4af3-8715-ec4a1602e1ec.png)

![image](https://user-images.githubusercontent.com/76723393/156124711-1dbcf5c4-beb2-4923-b09c-884a92074f60.png)

**Comment by Shivamddeveloper** [comment]
Issue Resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
