### ISSUE TITLE
Migration Issue 

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#169]
**Bug Name -** Migration Issue 
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 1.3.2
**Description -**

If anyone is using the previous version of the plugin and then updating the plugin, all running subscriptions are missed.
and then 
If you buying the subscription then my account - subscription tab is not opening.

![image](https://user-images.githubusercontent.com/76723393/156125033-1876830b-d163-491a-8ea0-8de79aa10e63.png)

**Comment by Shivamddeveloper** [comment]
Issue Resolved From my end. Please Note after updating Org Plugin You need to once deactivate Plugin then activate or plugin

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
