### ISSUE TITLE
Migration Issue.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#170]
**Bug Name -** Migration Issue.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 1.3.2
**Description -**

As you update the org then pro will be deactivated.

![image](https://user-images.githubusercontent.com/76723393/157249725-53ba3e10-f7c2-4dd4-a808-8914e65e806c.png)

**Comment by Shivamddeveloper** [comment]
There will be no issue in this, beacuse Pro(previous version) plugin need to be deactivate it is not compatible with lastest org Plugin

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
