### ISSUE TITLE
Migration Issue.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#171]
**Bug Name -** Migration Issue.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 1.3.2
**Description -**

Pro plugin is activated but on org GO PRO is displayed.

![image](https://user-images.githubusercontent.com/76723393/157252415-0998cd7a-7f9e-4e85-961d-97e141685c25.png)

**Comment by Shivamddeveloper** [comment]
i have fix this issue

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
