### ISSUE TITLE
Syntax Notice.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#173]
**Bug Name -** Syntax Notice.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.3.1
**WordPress Version -** 5.9
**Plugin Version -** 1.4.0
**Description -**

![image](https://user-images.githubusercontent.com/76723393/161269490-f9cf05b5-5e29-40dd-b6df-7c2169d01a75.png)

**Comment by Shivamddeveloper** [comment]
issue resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
