### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#174]
**Bug Name -** Notice.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.3.1
**WordPress Version -** 5.9
**Plugin Version -** 1.4.0
**Description -**

![image](https://user-images.githubusercontent.com/76723393/161272557-02202b34-a3fb-490e-a509-af1810eec252.png)

**Comment by Shivamddeveloper** [comment]
issue resolve now

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
