### ISSUE TITLE
Without having PRO plugin, Update Message is displayed. 

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#175]
**Bug Name -** Without having PRO plugin, Update Message is displayed. 
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.3.1
**WordPress Version -** 5.9
**Plugin Version -** 1.4.0
**Description -**

![image](https://user-images.githubusercontent.com/76723393/161273909-908072c5-602f-4e56-aef3-e4c7476e9e03.png)

**Comment by Shivamddeveloper** [comment]
i have resolve this issue

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
