### ISSUE TITLE
After updation plugin need to setup again.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#176]
**Bug Name -** After updation plugin need to setup again.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.3.1
**WordPress Version -** 5.9
**Plugin Version -** 1.4.0
**Description -**

![image](https://user-images.githubusercontent.com/76723393/162746283-8a110f6e-1cdd-49cc-af94-aaea71225f07.png)

**Comment by Shivamddeveloper** [comment]
issue fix
