### ISSUE TITLE
PHPCS Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#178]
**Bug Name -** PHPCS Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.7.0
**WordPress Version -** 6.0.1
**Plugin Version -** 1.4.2
**Description -**

[subscriptions-for-woocommerce.docx](https://github.com/wpswings/subscriptions-for-woocommerce/files/9130904/subscriptions-for-woocommerce.docx)

**Comment by Shivamddeveloper** [comment]
All Phpcs issue has been resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
