### ISSUE TITLE
PHPCS Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#180]
**Bug Name -** PHPCS Issues
**Area Path -** On Demo
**Status -** New
**Woo Commerce Version -** 6.8.2
**WordPress Version -** 6.0.1
**Plugin Version -** 1.4.3
**Description -**

[subscriptions-for-woocommerce.docx](https://github.com/wpswings/subscriptions-for-woocommerce/files/9422957/subscriptions-for-woocommerce.docx)

**Comment by Shivamddeveloper** [comment]
all phpcs issue is resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
