### ISSUE TITLE
Issue in service Icon

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#181]
**Bug Name -** Issue in service Icon
**Area Path -** On Local Setup
**Status -** New
**Woo Commerce Version -** 6.8.2
**WordPress Version -** 6.0.2
**Plugin Version -** 1.4.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/187724186-fa74cadb-dbfc-47e6-b551-736535dd548d.png)

**Comment by Shivamddeveloper** [comment]
i have checked this issue on multiple site and i got its working correclty
![Plugins-‹-Subscriptions-for-WooCommerce-Pro-Demo-WP-Swings-—-WordPress (2)](https://user-images.githubusercontent.com/87006389/187839995-b956df40-2836-4ea3-8ff8-5cbb3c4fc05d.png)

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
