### ISSUE TITLE
Sometimes when the subscription amount is decimal then issue payment will not proceed.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#184]
**Bug Name -** Sometimes when the subscription amount is decimal then issue payment will not proceed.
**Area Path -** On Code
**Status -** New
**Woo Commerce Version -** 7.0.0
**WordPress Version -** 6.0.2
**Plugin Version -** 1.4.5
**Description -**

You can check here-

**8xM8e&kQRx5PKUTv0NgPFW@$**

**https://demo.wpswings.com/userenv/demowps_I9cUo5ibQ25T/wp-admin/**

![image](https://user-images.githubusercontent.com/76723393/196174177-828f6676-ab8a-40d5-8c28-e6009e51a0e1.png)

**Comment by Shivamddeveloper** [comment]
this is not issue this happening with because you don't have proper setup of wps-paypal payment

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
