### ISSUE TITLE
Design Issue with Avada theme.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#185]
**Bug Name -** Design Issue with Avada theme.
**Area Path -** On Demo
**Status -** New
**Woo Commerce Version -** 7.0.0
**WordPress Version -** 6.0.2
**Plugin Version -** 1.4.5
**Description -**

Subscription table are not displaying properly.

![image](https://user-images.githubusercontent.com/76723393/196199619-f0db3300-4059-450b-b0a1-19bed814f465.png)

**Comment by Shivamddeveloper** [comment]
issue resolved

https://tinyurl.com/2m3ts67f

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
