### ISSUE TITLE
Product are not created which you are created during setup.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/subscriptions-for-woocommerce#187]
**Bug Name -** Product are not created which you are created during setup.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 7.1.1
**WordPress Version -** 6.0.2
**Plugin Version -** 1.4.7
**Description -**

![image](https://user-images.githubusercontent.com/76723393/207354724-6dc5f4dd-d5fe-4eb4-8a38-6de72b257eff.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
