### ISSUE TITLE
phpcs Issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#189]
**Woo Commerce Version** - 7.3.0
**WordPress Version** - 6.1.1
**Plugin Version** - 2.1.7
**Description** - phpcs Issues

[PHPcs.docx](https://github.com/wpswings/subscriptions-for-woocommerce/files/10707815/PHPcs.docx)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
