### ISSUE TITLE
phpcs Issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#193]
**Woo Commerce Version** - 7.5.1
**WordPress Version** - 6.2
**Plugin Version** - 1.4.9
**Description** - phpcs Issues

[PHPcs.docx](https://github.com/wpswings/subscriptions-for-woocommerce/files/11178923/PHPcs.docx)

**Comment by Shivamddeveloper** [comment]
all phpcs issue solved

**Comment by ashish-wps** [comment]
[PHPcs.docx](https://github.com/wpswings/subscriptions-for-woocommerce/files/11206991/PHPcs.docx)
 fixed
