### ISSUE TITLE
Show wrong Recurring amount in Subscription Table 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#196]
**Woo Commerce Version** - 7.6.1
**WordPress Version** - 6.2.2
**Plugin Version** - 1.5.1
**Description** -  Show wrong Recurring amount in Subscription Table  

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/260c70a6-4a1a-4ff2-9e95-fc6940a0f894)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/c8c036b9-32e9-4887-b8f5-219b0b2a8ee5)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
