### ISSUE TITLE
Recurring and Product Percent Discount coupon is not working when product signup amount is more than product amount.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#197]
**Woo Commerce Version** - 7.6.1
**WordPress Version** - 6.2.2
**Plugin Version** - 1.5.1
**Description** - Recurring and Product Percent Discount coupon is not working when product signup amount is more than product amount.

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/1f8b590f-65e3-43c3-a01b-69e2cbf5d5ed)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/25e75eb3-9414-4ecf-a44b-88ade8af537b)

**Comment by mohammaddanish-cedcoss** [comment]
works fine

**Comment by ashish-wps** [comment]
Fixed
