### ISSUE TITLE
Sign up fee issue on checkout page with Amazon Pay

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#199]
Woo Commerce Version - 7.8.1
WordPress Version - 6.2.2
Plugin Version - 1.5.2
Description - Sign up fee issue on checkout page with Amazon Pay

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/afaecaa7-b537-477d-a77e-94b2e9e752a8)

**Comment by Shivamddeveloper** [comment]
issue resolved

**Comment by ashish-wps** [comment]
Fixed
