### ISSUE TITLE
paypal Gateway is not working with Recurring discount coupon

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#200]
Woo Commerce Version - 8.0.0 beta 
WordPress Version - 6.2.2
Plugin Version - 2.1.8
Description - paypal Gateway is not working with Recurring discount coupon

![image](https://github.com/wpswings/woocommerce-subscriptions-pro/assets/105413021/ead45c19-9bdd-4839-a932-92e8aecc2d04)

**Comment by Shivamddeveloper** [comment]
solved

**Comment by ashish-wps** [comment]
Fixed
