### ISSUE TITLE
please set 1 as default value of "Free trial interval"

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#201]
Woo Commerce Version - 8.0.1
WordPress Version - 6.0.3
Plugin Version - 1.5.4
Description - please set 1 as default value of "Free trial interval"
**Note** - It's create wrong recurring amount with pro features.

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/67771c1f-e7ea-4b11-a58e-ca023656f41f)

**Comment by Shivamddeveloper** [comment]
no need to set 1 as default value of free trial interval, i have solved this issue

**Comment by ashish-wps** [comment]
Fixed
