### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#202]
**Woo Commerce Version** - 8.0.1
**WordPress Version** - 6.0.3
**Plugin Version** - 1.5.4
**Description** - phpcs issues

[PHPcs.docx](https://github.com/wpswings/subscriptions-for-woocommerce/files/12312568/PHPcs.docx)

**Comment by Shivamddeveloper** [comment]
solved

**Comment by ashish-wps** [comment]
Fixed
