### ISSUE TITLE
Show extra subscription feed on Dashboard

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#203]
**Woo Commerce Version** - 8.1.1
**WordPress Version** - 6.3.1
**Plugin Version** - 1.5.6
**Description** - Show extra subscription feed on Dashboard

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/76a0e900-2c0d-4a83-91ed-a61d22a25882)

**Comment by Shivamddeveloper** [comment]
issue solved

https://www.awesomescreenshot.com/image/43018380?key=132058e61ef4eaa29e3c0ed9867c253c

**Comment by ashish-wps** [comment]
Fixed
