### ISSUE TITLE
It's showing wrong product price on cart when user enable tax on product

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#204]
**Woo Commerce Version** - 8.1.1
**WordPress Version** - 6.3.1
**Plugin Version** - 1.5.6
**Description** - It's showing wrong product price on cart when user enable tax on product

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/7b9f7a97-3455-4c05-9615-85627b7e1962)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/ae977f71-8900-4a18-a451-0a1a28ded0b9)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/489011d6-d2dd-429e-8804-bea748c13ec6)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Fixed
