### ISSUE TITLE
When user enter "Free trial interval" than product value show 0 on cart page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#206]
**Woo Commerce Version** - 8.1.1
**WordPress Version** - 6.3.1
**Plugin Version** - 1.5.6
**Description** -  When user enter "Free trial interval" than product value show 0 on cart page

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/6f2a434b-4539-4d2e-b937-677def0bdace)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/5e703c1a-94f2-4fd1-ab4c-36e07b80117e)

**Comment by ashish-wps** [comment]
Still Exist 

[scrnli_03_10_2023_09-35-51.webm](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/a0374c13-768e-4015-af57-a1442dd6605d)

**Comment by Shivamddeveloper** [comment]
solved

**Comment by ashish-wps** [comment]
Fixed
