### ISSUE TITLE
When admin did not add Signup Fee than product price shows with tax

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#208]
**Woo Commerce Version** - 8.1.1
**WordPress Version** - 6.3.1
**Plugin Version** - 1.5.6
**Description** - When admin did not add Signup Fee than product price shows with tax

![Subs1](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/1a21850a-d863-4b68-b918-1aea78786929)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Still Exist

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/3f12fbb7-4a00-46e9-9476-21d62c23c3c3)


![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/4b5ada5a-fd01-4394-8f30-f6ca735a008b)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Fixed
