### ISSUE TITLE
show error when user enable the plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#209]
Woo Commerce Version - 8.2.1
WordPress Version - 6.3.2
Plugin Version - 1.5.6
Description - show error when user enable the plugin

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/4b971715-5700-468a-9e36-e3690785605e)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/2a0209a0-5142-4d03-9389-7f3d95d1a9c5)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
