### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#210]
**Woo Commerce Version** - 8.2.1
**WordPress Version** - 6.3.2
**Plugin Version** - 1.5.6
**Description** - fatal error 

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/8d57120e-fa22-4c82-adff-2916d3106f34)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
