### ISSUE TITLE
Subscription and Order status goes to pending when user use WPS Paypal and Paypal Standard

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#212]
**Woo Commerce Version** - 8.2.1
**WordPress Version** - 6.3.2
**Plugin Version** - 1.5.6
**Description** - Subscription and Order status goes to pending when user use WPS Paypal and Paypal Standard

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/39023401-fdbe-41e6-90e7-ff70a9639956)

**Comment by mohammaddanish-cedcoss** [comment]
work fine for WPS payment gateway
the Paypal standard handling the order status by woo-commerce itself

**Comment by ashish-wps** [comment]
okay
