### ISSUE TITLE
It shows the wrong product value when users increase the subscription product quantity

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#214]
Woo Commerce Version - 8.3.0
WordPress Version - 6.4.1
Plugin Version - 1.5.7
Description - It shows the wrong product value when users increase the subscription product quantity

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/ae1fde16-23d6-430c-be7a-aefde2057749)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/cb1b7005-15b1-4985-993f-58faa8142456)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
