### ISSUE TITLE
Subscription Order wasn't shown in the Subscription table

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#215]
Woo Commerce Version - 8.3.0
WordPress Version - 6.4.1
Plugin Version - 1.5.7
Description - Subscription Order wasn't shown in the Subscription table

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/97c7aac5-e523-4e7e-ae1f-5676f1149c49)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/123e6bd4-a179-44ce-bcda-191ea0d25795)

**Comment by mohammaddanish-cedcoss** [comment]
fixed
