### ISSUE TITLE
When user add signup fee so it's show incorrect recurring amount on checkout and Cart page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#216]
**Woo Commerce Version** - 8.3.0
**WordPress Version** - 6.4.1
**Plugin Version** - 1.5.8
**Description** - When user add signup fee so it's show incorrect recurring amount on checkout and Cart page

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/5d7de9ee-5f25-466b-b747-db212b7d1ed1)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/a6fb9a26-e62a-4ce1-a108-a358a757d927)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
It show wrong recurring amount some times.

![Screenshot from 2023-12-05 11-59-22](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/6d4cce22-ccdd-4e44-a196-8e39c290dd78)

**Comment by mohammaddanish-cedcoss** [comment]
checked but does not get the issue, please ignore this issue for now
