### ISSUE TITLE
Two subscription created with same parent id

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#218]
**Woo Commerce Version - 8.3.0
WordPress Version - 6.4.1
Plugin Version - 1.5.8
Description -** Two subscription created with same parent id

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/9455569b-32b3-45b8-bcb1-32be057ba6f8)

**Comment by mohammaddanish-cedcoss** [comment]
fixed
