### ISSUE TITLE
Product price shown with signup fee

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#219]
Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 1.5.8
Description - Product price shown with signup fee

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/098b4424-defa-441a-ae56-6dfc49c0d4dc)

**Comment by mohammaddanish-cedcoss** [comment]
fixed the issue

**Comment by ashish-wps** [comment]
Fixed
