### ISSUE TITLE
Recurring order is failed when user place order through Paypal Standards 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#222]
**Woo Commerce Version - 8.5.1
WordPress Version - 6.4.2
Plugin Version - 1.6.0
Description -** Recurring order is failed when user place order through Paypal Standards 

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/88d91940-225f-4ce3-8e26-bc2a1a6da30b)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/ea39583c-f3f3-4b09-a020-061f36e52760)

**Comment by mohammaddanish-cedcoss** [comment]
the error was coming due duplicate invoice id
please go to payment gateway setting add unique prefix in Invoice prefix setting

**Comment by ashish-wps** [comment]
okay
