### ISSUE TITLE
Initial signup fee should greater than or equal to 0

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#229]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 1.5.9
Description -** Initial signup fee should greater than or equal to 0

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/ef7072dd-1033-4fd1-b76e-e1b602dd7908)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
