### ISSUE TITLE
Please create new section for some advance section features.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#230]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 1.5.9
Description -** Please create new section for some advance section features.
**Note** - Please create a new section for prorate feature

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/7105b294-d3c7-4795-86fa-4895375e04f3)

**Comment by mohammaddanish-cedcoss** [comment]
discussed with Abhay sir, Will work in future, Please tag for this issue as an enhancement
