### ISSUE TITLE
ORG plugin didn't upload and show Incompatible Archive notice

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#231]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 1.5.9
Description -** ORG plugin didn't upload and show Incompatible Archive notice

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/5697f6ca-4f00-429d-987a-7742c48e8d69)

**Comment by mohammaddanish-cedcoss** [comment]
need to create a zip file, will do it for the final delivery of plugin, please ignore this issue for now

**Comment by ashish-wps** [comment]
Okay
