### ISSUE TITLE
Documentation for Triggering Renewal Events

### ISSUE THREAD

**Issue by e2corporation** [wpswings/subscriptions-for-woocommerce#232]
Hello Team WP Swings -- is there documentation provided in regards to Debugging procedures for triggering renewal payments for subscriptions in a local testing environment? When WP Swings creates a subscription order, there is no scheduled action entry created for a renewal event associated to the Subscription ID, even after the create renewal schedule job is run manually, there are no renewal events created. Please advise, thank you!

**Comment by ashish-wps** [comment]
we have instant recurring creation functionality, this functionality will allow you to test the recurring.
you need to create subscription product per day interval. after purchasing the product, a subscription plan will be created. you will need to go to subscription table, there will be option to create recurring

**Comment by e2corporation** [comment]
@ashish-wps Thanks for the feedback, can you elaborate more? Upon ordering a Virtual Subscription product with a 1-Day interval, there are no new Woo Commerce Scheduled Actions created. To clarify, I would like to trigger a renewal event to determine 1) What order status is being set on the order that is being renewed, and 2) If and what native webhooks are triggered when the order is renewed.
