### ISSUE TITLE
Order status getting pending when user place order from Paypal Standard

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#237]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.4.3
Plugin Version - 1.6.4
Description -** Order status getting pending when user place order from Paypal Standard

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/496676cb-03ce-4dbb-8a92-bc39bf489913)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Renewal getting Pending payment with Stripe and paypal

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/20afac99-87b7-4506-964e-c78a92faacee)

**Comment by mohammaddanish-cedcoss** [comment]
not an issue, the payment is handle through Paypal standard, there must be configuration issue

**Comment by ashish-wps** [comment]
Okay
