### ISSUE TITLE
on click href should redirect with particular subscription id filter and in this case only that subscription will be shown on that page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#238]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.4.3
Plugin Version - 1.6.4
Description -** on click ref should redirect with particular subscription id filter and in this case only that subscription will be shown on that page

**Suggest Order Note** - A new subscription is added with subscription ID 62. Click Here to check

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/52469281-2e6d-4989-b834-a8cc9a912aec)

**Comment by mohammaddanish-cedcoss** [comment]
done

**Comment by ashish-wps** [comment]
It"s show fatal error when order redirect to renewal subscription order

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/c3bb4d65-91ea-4186-96c2-81f0e2596ff3)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
