### ISSUE TITLE
Default Payment gateway visible in Subscription plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#243]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 1.6.6
Description -** Default Payment gateway visible in Subscription plugin

[scrnli_28_05_2024_17-33-44.webm](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/5aa6b8ba-60fa-4b7b-a197-af5260ce17af)

**Comment by Shivamddeveloper** [comment]
issue solved.

https://www.awesomescreenshot.com/video/28124443?key=8880bf6aceed169da3b56faab3c5a9c3
