### ISSUE TITLE
Cancel subscription cancel  status should update on Order status

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#244]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 1.6.6
Description -** Cancel subscription cancel  status should update on Order status

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/836f3708-52cd-4cfc-a2d0-88fd8cc68078)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/d5210bd6-e10b-489b-a6fe-e1e833f09c50)

**Comment by Shivamddeveloper** [comment]
this is not bug or enhancement because we provide to cancel the subscription order which is already working as you mention in above screen shot . and you are saying to cancel parent order of subscription which is logically wrong due to which it is not going work. so you can close this issue

**Comment by ashish-wps** [comment]
According to developer it's not an issue.
