### ISSUE TITLE
"Subscriptions Cancelled Successfully"  and "Subscriptions Deleted Successfully" should not appear when any subscription in not cancel or delete  

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#246]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 1.6.6
Description -** "Subscriptions Cancelled Successfully"  and "Subscriptions Deleted Successfully" should not appear when any subscription in not cancel or delete  

[scrnli_28_05_2024_18-29-54.webm](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/3ec8b1ac-d5b8-4891-bce1-f580f4b1de57)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/ed14b411-e30e-4b1f-b846-4aacb60efab7)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Fixed
