### ISSUE TITLE
Subscription Expiry Date should show in Subscription Details

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#247]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 1.6.6
Description -** Subscription Expiry Date should show in Subscription Details

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/089df17f-a129-4873-95a6-3d60ebfac6d1)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/0bfff5d2-9956-437c-a3a2-c60dceca6e09)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Fixed
