### ISSUE TITLE
Remove sign up fee for recurring payment in cart page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#248]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 1.6.6
Description -** Remove sign up fee for recurring payment in cart page

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/6f4d2a1c-09b2-409c-af98-6ac8e66606c4)

**Comment by Shivamddeveloper** [comment]
for now it is not easy task to solve this issue because in our subscription a common function is used to slow all data related to subscription either on cart item , or cart subtotal or checkout page . so you can keep this for future point in which i need to find other solution for same

**Comment by mohammaddanish-cedcoss** [comment]
i have remove this info, as we are already showing the renewal in the checkout page

**Comment by ashish-wps** [comment]
Okay
