### ISSUE TITLE
Free trial interval should not greater than subscription Expiry interval  

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#249]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 1.6.6
Description -** Free trial interval should not greater than subscription Expiry interval  

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/da580c4f-37b7-443a-a86b-82d04a5a11b1)

![image](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/b433e003-0209-48e3-9a14-371c62035e6a)

**Comment by Shivamddeveloper** [comment]
subscription free trial interval and expiry interval are not dependent value for any subscription , so in case if subscription free trial is greater than expirt interval then it does not create any issue , then respective date will automatically manage by plugin and it will not create any issue. hence it is not any bug so kindly close this issue

**Comment by ashish-wps** [comment]
According to developer it's not an issue.
