### ISSUE TITLE
Plugin feature should visible in Subscription for Woocommerce page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#250]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 1.6.6
Description -** Plugin feature should visible in Subscription for WooCommerce page
**Steps to reproduce -**
1. Install the WooCommerce plugin and setup the WooCommerce site
2. Install Subscription for WooCommerce plugin and activate the plugin
3. Click on Settings option
4. Verify the result.

[scrnli_29_05_2024_17-55-11.webm](https://github.com/wpswings/subscriptions-for-woocommerce/assets/105413021/20b86b1e-5803-4fa0-b9f5-ebcd5891186e)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Fixed
