### ISSUE TITLE
Subscription setting visible with selecting the subscription type in product page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#251]
**Woo Commerce Version - 9.1.2
WordPress Version - 6.6.0
Plugin Version - 1.6.9
Description -** Subscription setting visible with selecting the subscription type in product page

![image](https://github.com/user-attachments/assets/ccd62094-9396-482d-b50c-cb71e1fbe9d9)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
