### ISSUE TITLE
Expiry Interval should change when user select Subscriptions Per Interval

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#252]
**Woo Commerce Version - 9.1.2
WordPress Version - 6.6.0
Plugin Version - 1.6.9
Description -** Expiry Interval should change when user select Subscriptions Per Interval

![image](https://github.com/user-attachments/assets/a6d49d98-55b4-450a-994a-fee628f4588b)

![image](https://github.com/user-attachments/assets/ba09222b-1db4-4e3e-a249-5a0adf737525)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
