### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/subscriptions-for-woocommerce#253]
**Woo Commerce Version - 9.1.2
WordPress Version - 6.6.0
Plugin Version - 1.6.9
Description -** Fatal Error

![image](https://github.com/user-attachments/assets/9d2d4fe5-736c-462f-98a9-6bf151e62d4d)

![image](https://github.com/user-attachments/assets/ce241113-a065-4fc1-8210-c92e256df5d5)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
