### ISSUE TITLE
Allow Shop Managers to manage Subscriptions

### ISSUE THREAD

**Issue by ydwnj** [wpswings/subscriptions-for-woocommerce#259]
The issue occurs with the permissions in the plugin Subscriptions for WooCommerce. Specifically, the plugin restricts access to certain admin pages to only users with the manage_options capability, which excludes users like Shop Managers who have the manage_woocommerce capability but not manage_options.

**Affected Section:** The problematic section of code is in **class-subscriptions-for-woocommerce-admin.php**. The current implementation of the add_menu_page() and add_submenu_page() functions sets the required capability to manage_options, which is overly restrictive for Shop Managers and other users with WooCommerce management capabilities (manage_woocommerce).

**Problem:** When the Shop Manager role (or any other role with manage_woocommerce capabilities but without manage_options) tries to access the "Subscriptions for WooCommerce" admin pages, they are blocked, even though these users need access to manage subscriptions.

**Suggested Fix:** In the class-subscriptions-for-woocommerce-admin.php file, modify the add_menu_page() and add_submenu_page() functions to use the manage_woocommerce capability instead of manage_options. This will allow users with the manage_woocommerce capability (e.g., Shop Managers) to access the necessary admin pages without requiring full administrator access.

**Comment by mohammaddanish-cedcoss** [comment]
change the capability as manage_woocommerce
